#!/bin/sh

echo " Application is Use: "
$ ps -f --pid $(pgrep -u uname) /* username nya */

echo " Usage info status : \c"
if (%MEM>=1)
	echo ("memori almost full");
elif(%MEM<=0)
	echo("Memory is available");
else
	echo "Memory available is " %MEM " Remaining " 

fi
